### ISSUE TITLE
TeamCity Build trigged, but no builds running

### ISSUE THREAD

**Issue by arisliang** [Inedo/bmx-teamcity#21]
When triggering the team city build, this error happens quite frequently: "BuildMaster has triggered a build in TeamCity, but TeamCity indicates that there are no builds running at this time, therefore BuildMaster cannot wait until the build completes."

There IS a build queued in teamcity triggered by bm, but not running immediately. It looks like bm checked the status too fast, and jumped to the conclusion there's no build running.

What I do currently is to let bm to try on error a couple of times, but is there a better way to let bm to wait a bit longer for teamcity to start running the build? Because the issue is every time bm try again, it will trigger another build unnecessarily.

**Comment by jrasch** [comment]
This was fixed in #20. It's not fully released to the Den yet but you can download the extension manually from http://44.inedo.com/buildmaster/extensions/TeamCity5.2.2.bmx and install it manually.

**Comment by arisliang** [comment]
I've installed the 5.2.2 manually, it seems the problem still exists.
